// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1pVfL_wJx2ml2PRiYF4Go_ACmUc8SOA',
    appId: '1:1040034403665:web:22080e974e2aa28371ef70',
    messagingSenderId: '1040034403665',
    projectId: 'tp3-flutter-b02d7',
    authDomain: 'tp3-flutter-b02d7.firebaseapp.com',
    storageBucket: 'tp3-flutter-b02d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7rY0hfc1CNaqZogiYn_zdBi8VEjzbbY',
    appId: '1:1040034403665:android:8095d76cc0f451e271ef70',
    messagingSenderId: '1040034403665',
    projectId: 'tp3-flutter-b02d7',
    storageBucket: 'tp3-flutter-b02d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ksvBOAO1XDxKxxCs2j2ZbBDdcUxea-U',
    appId: '1:1040034403665:ios:c2c892caf262749271ef70',
    messagingSenderId: '1040034403665',
    projectId: 'tp3-flutter-b02d7',
    storageBucket: 'tp3-flutter-b02d7.appspot.com',
    iosBundleId: 'com.example.tp3Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ksvBOAO1XDxKxxCs2j2ZbBDdcUxea-U',
    appId: '1:1040034403665:ios:c2c892caf262749271ef70',
    messagingSenderId: '1040034403665',
    projectId: 'tp3-flutter-b02d7',
    storageBucket: 'tp3-flutter-b02d7.appspot.com',
    iosBundleId: 'com.example.tp3Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi1pVfL_wJx2ml2PRiYF4Go_ACmUc8SOA',
    appId: '1:1040034403665:web:cfa0a9af628cbf4371ef70',
    messagingSenderId: '1040034403665',
    projectId: 'tp3-flutter-b02d7',
    authDomain: 'tp3-flutter-b02d7.firebaseapp.com',
    storageBucket: 'tp3-flutter-b02d7.appspot.com',
  );
}
